services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: ""
    startCommand: gunicorn myProject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myProject.settings
