# Generated by Django 5.1.1 on 2024-10-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_page',
            name='Username',
            field=models.CharField(max_length=30),
        ),
    ]
