# Generated by Django 5.1.2 on 2024-10-28 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +999999999 or 999999999.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Zip_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='ZIP code must be in the format: 12345 or 12345-6789.', regex='^\\d{5}(-\\d{4})?$')]),
        ),
    ]
