# Generated by Django 5.1.2 on 2024-10-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_purchase_email_alter_purchase_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.CharField(max_length=100)),
            ],
        ),
    ]
